"""Add Conversation and ConversationMember models

Revision ID: 3e23b93c172a
Revises: 06bb669fb78e
Create Date: 2025-06-02 00:46:22.078899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e23b93c172a'
down_revision = '06bb669fb78e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_member',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name='fk_conversation_member_conversation_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_conversation_member_user_id'),
    sa.PrimaryKeyConstraint('conversation_id', 'user_id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_message_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_foreign_key('fk_message_conversation_id', 'conversation', ['conversation_id'], ['id'])
        batch_op.create_foreign_key('fk_message_sender_id', 'user', ['sender_id'], ['id'])
        batch_op.drop_column('is_private')
        batch_op.drop_column('username')
        batch_op.drop_column('recipient_username')
        batch_op.drop_column('message_content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_content', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('recipient_username', sa.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('is_private', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint('fk_message_sender_id', type_='foreignkey')
        batch_op.drop_constraint('fk_message_conversation_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_message_conversation_id'))
        batch_op.drop_column('is_read')
        batch_op.drop_column('content')
        batch_op.drop_column('sender_id')
        batch_op.drop_column('conversation_id')

    op.drop_table('conversation_member')
    op.drop_table('conversation')
    # ### end Alembic commands ###
