"""Add User model for login/register

Revision ID: 72442c1358d8
Revises: d368a6500ebf
Create Date: 2025-05-29 23:40:36.411212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72442c1358d8'
down_revision = 'd368a6500ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
