"""Rename message_content to content in message table

Revision ID: a81191c56316
Revises: 3e23b93c172a
Create Date: 2025-06-02 11:22:45.809716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a81191c56316'
down_revision = '3e23b93c172a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_content', sa.Text(), nullable=False))
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=False))
        batch_op.drop_column('message_content')

    # ### end Alembic commands ###
